import { describe, expect, it } from 'vitest'
import { totpCode, parseTotp } from '@/lib/vault/totp'
import type { Item, ItemContent } from '@/lib/vault/types'
import { copyFieldsOf, isSecret, textToCopy } from './copyText'

const item = (content: ItemContent): Item => ({ id: 'i', vaultId: 'v', content, createdAt: null, updatedAt: null })
// The seed of RFC 6238's SHA-1 vectors, in base32.
const SEED = 'GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ'

describe('what a row copies', () => {
  it('offers only the buttons that would copy something', () => {
    expect(copyFieldsOf(item({ name: 'a', password: 'p' }))).toEqual(['password'])
    expect(copyFieldsOf(item({ name: 'a', username: 'u', password: 'p', totp: SEED }))).toEqual([
      'username',
      'password',
      'code',
    ])
  })

  it('copies the username and the password as they are', async () => {
    const entry = item({ name: 'a', username: 'ada', password: 's3cr3t' })

    expect(await textToCopy(entry, 'username')).toBe('ada')
    expect(await textToCopy(entry, 'password')).toBe('s3cr3t')
  })

  it('copies the code of this moment, generated by the web TOTP', async () => {
    const entry = item({ name: 'a', totp: SEED })
    const at = 59_000

    expect(await textToCopy(entry, 'code', at)).toBe(await totpCode(parseTotp(SEED), at))
  })

  it('clears the password and the code from the clipboard, and not the username', () => {
    expect(isSecret('password')).toBe(true)
    expect(isSecret('code')).toBe(true)
    expect(isSecret('username')).toBe(false)
  })
})
