import * as React from "react"
import { Dialog as DialogPrimitive } from "@base-ui/react/dialog"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { XIcon } from "lucide-react"

/**
 * Returns the focus to whatever opened the dialog, which nothing was doing (#360).
 *
 * BASE UI ALREADY DOES THIS — when the dialog is opened by its `Trigger`. Every dialog
 * in this application is mounted instead: the screen renders `{editing && <ItemDialog/>}`
 * with `open` hard-wired, so there is no trigger element for the primitive to go back
 * to, and closing left the focus on `document.body`.
 *
 * With 370 entries that is not a detail. Somebody navigating by keyboard who opens an
 * entry and cancels is put back at the top of the page and has to tab through the whole
 * list again.
 *
 * REPRODUCED WITH REAL INTERACTION BEFORE TOUCHING ANYTHING, because #360 was observed
 * with a programmatic `click()` and that could have been the artefact: it fails the same
 * with a real click on Cancel, with Escape, and with Enter on Cancel after opening the
 * row with the keyboard.
 *
 * The opener is captured in a state initialiser and NOT in an effect, and the difference
 * decides whether this works: child effects run before the parent's, so by the time an
 * effect here could look, the dialog has already focused its first field and
 * `document.activeElement` is that field. The initialiser runs during the first render,
 * before any of that.
 *
 * `isConnected` IS THE HALF THAT MAKES IT HONEST. What opened the dialog may be gone by
 * the time it closes — a virtualised row scrolled out of the list, or the very entry the
 * delete dialog just removed. Focusing a detached node does nothing silently, so it is
 * checked; when there is nowhere to go back to, the focus is left where it is rather
 * than sent somewhere arbitrary.
 */
function Dialog({ ...props }: DialogPrimitive.Root.Props) {
  const [opener] = React.useState(() =>
    typeof document === "undefined" ? null : (document.activeElement as HTMLElement | null)
  )

  React.useEffect(
    () => () => {
      if (opener?.isConnected && typeof opener.focus === "function") opener.focus()
    },
    [opener]
  )

  return <DialogPrimitive.Root data-slot="dialog" {...props} />
}

function DialogTrigger({ ...props }: DialogPrimitive.Trigger.Props) {
  return <DialogPrimitive.Trigger data-slot="dialog-trigger" {...props} />
}

function DialogPortal({ ...props }: DialogPrimitive.Portal.Props) {
  return <DialogPrimitive.Portal data-slot="dialog-portal" {...props} />
}

function DialogClose({ ...props }: DialogPrimitive.Close.Props) {
  return <DialogPrimitive.Close data-slot="dialog-close" {...props} />
}

function DialogOverlay({
  className,
  ...props
}: DialogPrimitive.Backdrop.Props) {
  return (
    <DialogPrimitive.Backdrop
      data-slot="dialog-overlay"
      className={cn(
        "fixed inset-0 isolate z-50 bg-black/10 duration-100 supports-backdrop-filter:backdrop-blur-xs data-open:animate-in data-open:fade-in-0 data-closed:animate-out data-closed:fade-out-0",
        className
      )}
      {...props}
    />
  )
}

function DialogContent({
  className,
  children,
  showCloseButton = true,
  ...props
}: DialogPrimitive.Popup.Props & {
  showCloseButton?: boolean
}) {
  return (
    <DialogPortal>
      <DialogOverlay />
      <DialogPrimitive.Popup
        data-slot="dialog-content"
        className={cn(
          /*
           * `max-h` AND `overflow-y-auto` ARE NOT STYLING: WITHOUT THEM A TALL DIALOG IS
           * UNREACHABLE ON A PHONE. See #437.
           *
           * The popup is centred with `-translate-y-1/2`, so anything taller than the
           * viewport spills EQUALLY above and below — the title goes off the top and the
           * buttons off the bottom. And Base UI locks the body's scroll while a dialog is
           * open, so there is no scroll anywhere to reach them with. Measured on the item
           * dialog at 664px of viewport height: 844px tall, `top: -90`, `bottom: 754`.
           *
           * `dvh` AND NOT `vh`, which is the half that only matters on the device that has
           * the problem: on iOS Safari the address bar grows and shrinks as you scroll, and
           * `vh` is fixed to the LARGE viewport — the one where the bar is collapsed. A
           * dialog sized with `vh` is still taller than what you can see at the moment it
           * opens, which is exactly when the buttons are needed.
           *
           * THIS FILE IS GENERATED BY THE shadcn CLI, so regenerating the component drops
           * this. It is written here rather than in one screen because the defect belongs
           * to the dialog: fixing it in `ItemDialog` alone would leave every other one
           * waiting for somebody to add a field to it.
           */
          "fixed top-1/2 left-1/2 z-50 grid max-h-[calc(100dvh-2rem)] w-full max-w-[calc(100%-2rem)] -translate-x-1/2 -translate-y-1/2 gap-4 overflow-y-auto rounded-xl bg-popover p-4 text-sm text-popover-foreground ring-1 ring-foreground/10 duration-100 outline-none sm:max-w-sm data-open:animate-in data-open:fade-in-0 data-open:zoom-in-95 data-closed:animate-out data-closed:fade-out-0 data-closed:zoom-out-95",
          className
        )}
        {...props}
      >
        {children}
        {showCloseButton && (
          <DialogPrimitive.Close
            data-slot="dialog-close"
            render={
              <Button
                variant="ghost"
                className="absolute top-2 right-2"
                size="icon-sm"
              />
            }
          >
            <XIcon
            />
            <span className="sr-only">Close</span>
          </DialogPrimitive.Close>
        )}
      </DialogPrimitive.Popup>
    </DialogPortal>
  )
}

function DialogHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="dialog-header"
      className={cn("flex flex-col gap-2", className)}
      {...props}
    />
  )
}

function DialogFooter({
  className,
  showCloseButton = false,
  children,
  ...props
}: React.ComponentProps<"div"> & {
  showCloseButton?: boolean
}) {
  return (
    <div
      data-slot="dialog-footer"
      className={cn(
        "-mx-4 -mb-4 flex flex-col-reverse gap-2 rounded-b-xl border-t bg-muted/50 p-4 sm:flex-row sm:justify-end",
        className
      )}
      {...props}
    >
      {children}
      {showCloseButton && (
        <DialogPrimitive.Close render={<Button variant="outline" />}>
          Close
        </DialogPrimitive.Close>
      )}
    </div>
  )
}

function DialogTitle({ className, ...props }: DialogPrimitive.Title.Props) {
  return (
    <DialogPrimitive.Title
      data-slot="dialog-title"
      className={cn(
        "font-heading text-base leading-none font-medium",
        className
      )}
      {...props}
    />
  )
}

function DialogDescription({
  className,
  ...props
}: DialogPrimitive.Description.Props) {
  return (
    <DialogPrimitive.Description
      data-slot="dialog-description"
      className={cn(
        "text-sm text-muted-foreground *:[a]:underline *:[a]:underline-offset-3 *:[a]:hover:text-foreground",
        className
      )}
      {...props}
    />
  )
}

export {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
}
